### ISSUE TITLE
civicrm db user has insufficient permissions

### ISSUE THREAD

**Issue by krschmidt** [LaneCommunityCollege/eugenecoderdojo#17]
I've removed the username and table name.

```
Error message
SQLSTATE[42000]: Syntax error or access violation: 1142 SELECT command denied to user 'username'@'localhost' for table 'civi-table'
```

**Comment by krschmidt** [comment]
Tried adding select permissions for the drupal mysql user. Also regenerated the table prefixes for civicrm based on https://wiki.civicrm.org/confluence/display/CRMDOC/Views3+Integration, but that didn't work either.

**Comment by krschmidt** [comment]
To get the error message to show up, navigate to https://eugeneregioncoderdojo.org/sessions and edit the view - error shows in preview

**Comment by jerrac** [comment]
Um, I thought that user had full permissions to everything? Odd.

**Comment by krschmidt** [comment]
User did have full permissions to everything; the prefixes for the civicrm tables in settings.php were incorrect - despite having been generated by civicrm itself. Fixed.
