### ISSUE TITLE
PHP needs more memory

### ISSUE THREAD

**Issue by krschmidt** [LaneCommunityCollege/eugenecoderdojo#19]
See error log for site.

**Comment by jerrac** [comment]
I gave the LVE more ram. Did that help?

**Comment by krschmidt** [comment]
Actually, you probably didn't even need to do that - did you change how much memory was available to PHP about 6 weeks ago? 

I was really hoping that adding more memory would have helped fix some of #7 , but it doesn't look like it did.

**Comment by krschmidt** [comment]
Marking this as fixed, since no new memory errors have cropped up.
