### ISSUE TITLE
Install admin_menu

### ISSUE THREAD

**Issue by jerrac** [LaneCommunityCollege/eugenecoderdojo#28]
The admin_menu module is a lot easier to navigate than what is currently there. 

Is there any reason not to install it?

**Comment by krschmidt** [comment]
I'll concede it's a lot easier to sue, but I'm not sure Vallie would benefit from it, given the limited number of administrative tasks she actually uses. Also, we'd need to verify it plays nicely with the extra menu civicrm adds

**Comment by jerrac** [comment]
If it's easier to use, wouldn't Vallie benefit?

**Comment by krschmidt** [comment]
It's easier to use for an administrator; but Vallie isn't an administrator. There's a limited set of tasks Vallie performs on that side, most of which are through CiviCRM, which has its own drop down menu. Plus I'm still nervous to install any more modules until #7 is decisively fixed.

**Comment by jerrac** [comment]
Does she have her own dashboard or something? I know there are several modules out there aimed at making it easier for users to deal with the admin stuff they need to do.

**Comment by krschmidt** [comment]
CiviCRM has its own dashboard and drop down that only show when CiviCRM is active. My understanding is that Vallie has surprisingly little regular interaction with Drupal itself, beyond getting feedback from feedback forms. Everything else is incidental. She used to have a set of shortcuts configured for her, which is probably a better option based on my understanding of her workflow. I'm closing, unless there's been a specific request from her.
