### ISSUE TITLE
site fails to correctly deploy

### ISSUE THREAD

**Issue by krschmidt** [LaneCommunityCollege/eugenecoderdojo#3]
When pushing any changes, files are deployed with 0755 permissions, which cpanel decides is a security risk, refusing to render any files at all. This includes trivial files, like the readme. 

@andersonpr fixed by changing parent directory and php files  to 0744, then I set sites/default/files according to drupal docs, but this breaks on next deployment.

**Comment by jerrac** [comment]
I made a couple changes to the deploy script. Did it work? I'm not seeing any errors when browsing.

Never mind, the deploy failed...

**Comment by jerrac** [comment]
I believe the issue is fixed. Can you confirm?

**Comment by andersonpr** [comment]
Don't see group writes on any of the files, and public_html looks fine. Looks like this issue's fixed.

**Comment by krschmidt** [comment]
Installed xmlsitemap (#3), pushed a commit, travis reports the build is ok... but no sign of xmlsitemap

**Comment by krschmidt** [comment]
directory is now present, but no sign of files.

**Comment by jerrac** [comment]
I'm working on it.

**Comment by jerrac** [comment]
No luck... I have travis successfully setting the owner/group by numeric ids before rsyncing the files over. But when it rsyncs, rsync sets the group to the user, instead of to what I set it to. Which causes the 403 errors. Hmm...

**Comment by jerrac** [comment]
Fixed.

**Comment by krschmidt** [comment]
I've pushed a few things this evening, in ref to #9. Not only are changes not showing up, but the hook is showing a 500 error.

**Comment by jerrac** [comment]
Ah, I'm not using webhooks. Still using travis. Travis showed that a previous git process had left behind a .git/index.lock file. I deleted that file and restarted the deploy. See https://travis-ci.org/LaneCommunityCollege/eugenecoderdojo for the status.

**Comment by jerrac** [comment]
It completed this time. Can you see about getting https://github.com/LaneCommunityCollege/eugenecoderdojo/issues/6 fixed?

**Comment by krschmidt** [comment]
Job finished, but the last several commits haven't applied - ba0115ea1ef5e36e667c84cc624778571c19ecc7, d59a71887414e2f013dc4a2c95255d6202fb05bc, or 8b8a5ca6c326e9409a101d2775599e9656da0769. Probably others.

**Comment by jerrac** [comment]
You were removing modules right? I did not add the --delete flag to the rsync command, so the modules would not be removed. 

Ok, since I can't recall why I wanted to avoid just using git and no rsync, I'll move things around to use git for the full deployment.

**Comment by krschmidt** [comment]
currently getting a 500 error

**Comment by jerrac** [comment]
see the xkcd I linked to in hipchat.

**Comment by jerrac** [comment]
Wow this site hates me...

cPanel was running php with suphp. And it was overly strict with permissions. So, after much effort, I got it to use php-fpm instead. 'Course, in order to make sure I didn't break other sites on the server, I had to tell coderdojo to use php-5.5 and cpanel to only use fpm with php-5.5... 

Here's hoping this stays fixed...

**Comment by krschmidt** [comment]
Now I'm getting a WSOD trying to load /admin/modules - probably due to this

```
Allowed memory size of 33554432 bytes exhausted (tried to allocate 331662 bytes)
```

**Comment by krschmidt** [comment]
Now new issues:

```
Error message
Warning: fileowner(): stat failed for temporary://update_PMHZFH in update_manager_local_transfers_allowed() 
```

**Comment by jerrac** [comment]
the site is in a different docroot, so the /tmp path changed. I believe I have fixed it by setting the temporary directory to ../../tmp.

**Comment by krschmidt** [comment]
I think this one is finally done - another commit deployed successfully, status report shows as green.
