### ISSUE TITLE
SSL Cert

### ISSUE THREAD

**Issue by krschmidt** [LaneCommunityCollege/eugenecoderdojo#6]
Something from Lets Encrypt would be ideal.

@jerrac or @andersonpr, any chance you could take this one on?

**Comment by andersonpr** [comment]
I'll take this one on.

**Comment by jerrac** [comment]
cpanel has a Lets Encrypt plugin that can deal with this. I was going to
run it after the dns propagated. Do I still need to?

**Comment by jerrac** [comment]
@krschmidt Does the .htaccess file have the lines that let letsencrypt work? See: https://www.drupal.org/node/2408321

**Comment by krschmidt** [comment]
https://github.com/LaneCommunityCollege/eugenecoderdojo/blob/master/public_html/.htaccess

doesn't look like it. This depends on #3 then. Then we can apply the patch at https://www.drupal.org/files/issues/d7-support_rfc_5785_by-2408321-53.patch

**Comment by jerrac** [comment]
@krschmidt Can you get the .htaccess file updated?

**Comment by krschmidt** [comment]
@jerrac .htaccess file should be updated so soon as the build finishes

**Comment by jerrac** [comment]
LetsEncrypt cert is live.

**Comment by krschmidt** [comment]
thanks!
